### ISSUE TITLE
XML declaration

### ISSUE THREAD

**Issue by dkotrada** [olaven/serialize-xml#5]
How can I create an XML declaration like this.

`<?xml version="1.0"?>`

and 

`<?xml version="1.0" encoding="UTF-8" ?>`

**Comment by olaven** [comment]
Hi! Thanks for checking out the library! 

Based on your suggestion, I have implemented an api for declarations over at #6 👍 
Please let me know what you think about it, and I'll include it in the next release!

**Comment by dkotrada** [comment]
Cool I will check it asap.

**Comment by olaven** [comment]
Great! Let me know if you have any feedback. 
I'll probably create a new release before long 👍

**Comment by dkotrada** [comment]
Here is how I use it. I wrote a class should work the same as `tag` function. 

``` ts
const xml = tag("TagLevelOne", [
  tag("TagLevelTwo", [
    tag("SubSubTagOne", "content_of_sub_sub_tag_one"),
    tag("SubSubTagTwo", "content_of_sub_sub_tag_two"),
  ], [
    ["tag_level_two_key", "tag_level_two_value"],
    ["tag_level_two_another_key", "tag_level_two_another_value"],
  ]),
]);
``` 

Thank You.

```ts
import {
  serialize,
  declaration,
  Tag,
} from "https://raw.githubusercontent.com/olaven/serialize-xml/6fda66214443875a4f25057ca185b71d63596cd5/mod.ts";

class XmlTag implements Tag {
  // tagname
  name: string;
  // a new tag inside or content inside tagname as string
  children: Tag[] | string;
  // key, value pars  [ [ "", ""] ]
  attributes: [string, string][];

  constructor(
    name: string,
    children: Tag[] | string = "",
    attributes: [string, string][] = [],
  ) {
    this.name = name;
    this.children = children;
    this.attributes = attributes;
  }
}

const xml = new XmlTag("TagLevelOne", [
  new XmlTag(
    "TagLevelTwo",
    [
      new XmlTag("SubSubTagOne", "content_of_sub_sub_tag_one"),
      new XmlTag("SubSubTagTwo", "content_of_sub_sub_tag_two"),
    ],
    [
      ["tag_level_two_key", "tag_level_two_value"],
      ["tag_level_two_another_key", "tag_level_two_another_value"],
    ],
  ),
]);
const file_content =
  serialize(declaration([["version", "1.0"], ["encoding", "UTF-8"]])) +
  serialize(xml);

console.log(file_content);
/**
<?xml version="1.0" encoding="UTF-8"?>
<TagLevelOne>
    <TagLevelTwo tag_level_two_key="tag_level_two_value" tag_level_two_another_key="tag_level_two_another_value">
        <SubSubTagOne>content_of_sub_sub_tag_one</SubSubTagOne>
        <SubSubTagTwo>content_of_sub_sub_tag_two</SubSubTagTwo>
    </TagLevelTwo>
</TagLevelOne>
*/
``

**Comment by olaven** [comment]
Thanks! The next release (currently on the same branch) will allow for mulitple arguments to serialize, meaning that you don't have to concatinate two serialize-results yourself, i.e. `const xml = serialize(first_tag, second_tag)`. 

Based on your use, it looks like it would be easier for you to use the `tag`-function than the class :) I.e. `tag("tagLevelTwo", [tag("child", "content"]], [["key": "value:"]])`. But you do you, of course 😄 

Does that make sense?

**Comment by olaven** [comment]
`0.3.2`is now released. Thanks for feedback! 
I am closing this issue, but feel free to reopen if something is unclear 👍
